name: Update badges

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0 * * 0'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: toadfans/obsidian-plugin-badges@main
